Add missing pip requirement for `flaskext.mysql`.
Fixes:

```
$ python Main.py
Traceback (most recent call last):
  File "/Users/seb/src/github.com/nicbov/EatRight/Main.py", line 2, in <module>
    from flaskext.mysql import MySQL
ModuleNotFoundError: No module named 'flaskext'
```